// Mock types for Prisma Client until the actual schema is available

declare module '@prisma/client' {
  export interface Camera {
    id: string;
    name: string;
    ipAddress: string;
    port: number;
    username?: string | null;
    password?: string | null;
    manufacturer?: string | null;
    model?: string | null;
    firmware?: string | null;
    isActive: boolean;
    isOnline?: boolean;
    lastSeen?: Date | null;
    createdAt: Date;
    updatedAt: Date;
    rtspUrl?: string | null;
    snapshotUrl?: string | null;
    streamUrl?: string | null;
    timezone?: string | null;
    location?: string | null;
    description?: string | null;
    isEncrypted: boolean;
    encryptionKey?: string | null;
    recordingEnabled: boolean;
    motionDetectionEnabled: boolean;
    motionSensitivity?: number | null;
    recordingRetentionDays: number;
    storagePath?: string | null;
    groupId?: string | null;
    userId: string;
    status?: string | null;
    lastRecordingAt?: Date | null;
    lastMotionAt?: Date | null;
    lastError?: string | null;
    lastErrorAt?: Date | null;
    isRecording: boolean;
    isStreaming: boolean;
    isMotionDetected: boolean;
    isAudioEnabled: boolean;
    isHdEnabled: boolean;
    isInfraredEnabled: boolean;
    isNightVisionEnabled: boolean;
    isPtzEnabled: boolean;
    isAudioSupported: boolean;
    isHdSupported: boolean;
    isInfraredSupported: boolean;
    isNightVisionSupported: boolean;
    isPtzSupported: boolean;
    isCloudStorageEnabled: boolean;
    cloudStoragePath?: string | null;
    cloudStorageProvider?: string | null;
    cloudStorageStatus?: string | null;
    cloudStorageLastSync?: Date | null;
    cloudStorageError?: string | null;
    cloudStorageQuotaUsed?: number | null;
    cloudStorageQuotaTotal?: number | null;
    cloudStorageQuotaUnit?: string | null;
    cloudStorageQuotaPercent?: number | null;
    cloudStorageIsFull: boolean;
    cloudStorageIsEnabled: boolean;
    cloudStorageIsSyncing: boolean;
    cloudStorageLastError?: string | null;
    cloudStorageLastSyncDuration?: number | null;
    cloudStorageLastSyncSize?: number | null;
    cloudStorageLastSyncFiles?: number | null;
    cloudStorageLastSyncStatus?: string | null;
    cloudStorageLastSyncStartedAt?: Date | null;
    cloudStorageLastSyncCompletedAt?: Date | null;
    cloudStorageLastSyncErrorAt?: Date | null;
    cloudStorageLastSyncErrorCount: number;
    cloudStorageLastSyncWarningCount: number;
    cloudStorageLastSyncInfo?: string | null;
    cloudStorageLastSyncWarning?: string | null;
    cloudStorageLastSyncError?: string | null;
    cloudStorageLastSyncStats?: Record<string, any> | null;
    cloudStorageConfig?: Record<string, any> | null;
    cloudStorageMetadata?: Record<string, any> | null;
    cloudStorageTags?: string[] | null;
    cloudStorageIsConnected: boolean;
    cloudStorageConnectionTestedAt?: Date | null;
    cloudStorageConnectionStatus?: string | null;
    cloudStorageConnectionError?: string | null;
    cloudStorageConnectionRetryCount: number;
    cloudStorageConnectionLastRetryAt?: Date | null;
    cloudStorageConnectionLastSuccessAt?: Date | null;
    cloudStorageConnectionLastErrorAt?: Date | null;
    cloudStorageConnectionLastError?: string | null;
    cloudStorageConnectionLastWarning?: string | null;
    cloudStorageConnectionLastInfo?: string | null;
    cloudStorageConnectionStats?: Record<string, any> | null;
    cloudStorageConnectionConfig?: Record<string, any> | null;
    cloudStorageConnectionMetadata?: Record<string, any> | null;
    cloudStorageConnectionTags?: string[] | null;
  }
}

// This allows TypeScript to recognize the Camera type when imported from @prisma/client
export {};
